# Generated by Django 5.2.17 on 2026-09-18 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('account_created', 'Account created'), ('project_created', 'Project created'), ('project_updated', 'Project updated'), ('project_completed', 'Project completed'), ('member_added', 'Member added'), ('member_removed', 'Member removed'), ('task_created', 'Task created'), ('task_updated', 'Task updated'), ('task_status_changed', 'Task status changed'), ('task_assigned', 'Task assigned'), ('task_completed', 'Task completed')], max_length=40)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'activity logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='activity_ac_project_eaf88d_idx')],
            },
        ),
    ]
